name: Minify and Deploy to GitHub Pages

on:
  push:
    branches: [main, test-workflow]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Minify HTML
        run: |
          mkdir -p dist
          node minify.js
    
      - name: Show contents of docs folder
        run: ls -R docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: publish
          publish_dir: ./dist